# SwiftLint configuration for swift-incits-4-1986
# Inherits from the shared parent configuration in swift-standards

parent_config: https://raw.githubusercontent.com/swift-standards/swift-standards/main/.swiftlint.yml

# Package-specific overrides
# Disable type_name validation because test suites use lowercase method names like "detect()", "isAllASCII()"
disabled_rules:
  - type_name
